spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/medicine?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-circular-references: true
  security:
    user:
      name: kaven
      password: itkaven
      roles: USER
  mvc:
    #    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  transaction:
    rollback-on-commit-failure: true
    web:
      resources:
        static-locations: classpath:/static/
  thymeleaf:

    #验证模板是否存在

    check-template: false

    check-template-location: false

    ##模板的模式，支持 HTML, XML TEXT JAVASCRIPT等

    mode: HTML5

    suffix: .html

    #模板路径 -可以修改

    prefix: classpath:/templates/

    #编码格式 不必填

    encoding: utf-8

    #内容类别 不必填

    servlet:

      content-type: text/html

    #开发配置为false，避免修改模板还要重启

    cache: false
logging:
  level:
    org:
      springframework:
        security: DEBUG

#      spring.servlet.multipart.max-file-size : 100MB
#      spring.servlet.multipart.max-request-size: 100MB
#      max-http-header-size: 102400

#  mvc:
#    static-path-pattern:  static/**
server:
  servlet:
    session:
      timeout: 7200
  max-http-header-size: 16384
  port: 8081
mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
